services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: upbeat-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./learning_plans:/app/learning_plans
      - ./user_data:/app/user_data
    env_file:
      - .env
    networks:
      - upbeat-network
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: upbeat-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - upbeat-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - api
    restart: unless-stopped

networks:
  upbeat-network:
    driver: bridge